blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/simulsol
    about: Join our Discord server for questions, discussions, and community support
  - name: 📖 Documentation
    url: https://docs.simulsol.dev
    about: Check our documentation for guides, tutorials, and API references
  - name: 🤔 GitHub Discussions
    url: https://github.com/your-org/simulsol/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📧 Contact Support
    url: mailto:support@simulsol.dev
    about: Email us for technical support and general inquiries